# Generated by Django 4.1.3 on 2022-12-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_aboutmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='slug',
        ),
    ]
